### ISSUE TITLE
Decoding error when running za_hansard_pmg_api_scraper command

### ISSUE THREAD

**Issue by chrismytton** [mysociety/za-hansard#76]
We're seeing the following error when running the `za_hansard_pmg_api_scraper` command via Pombola's [`update_za_hansard.bash` script](https://github.com/mysociety/pombola/blob/4bca5f2046928590afe11c1b7f710fdd0a27f780/bin/update_za_hansard.bash).

```
handling committee: Sport, Recreation, Arts & Culture
No events for that committee!
=======================================
handling committee: Transport EC
No events for that committee!
=======================================
Traceback (most recent call last):
  File "./manage.py", line 70, in <module>
    execute_from_command_line(sys.argv)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/src/za-hansard/za_hansard/management/commands/za_hansard_pmg_api_scraper.py", line 530, in handle
    self.handle_committee(committee)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/src/za-hansard/za_hansard/management/commands/za_hansard_pmg_api_scraper.py", line 303, in handle_committee
    self.stdout.write(u"handling committee: {0}\n".format(committee['name']).encode('utf-8'))
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 111, in write
    if ending and not msg.endswith(ending):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 25: ordinal not in range(128)
```

**Comment by chrismytton** [comment]
I _think_ https://github.com/mysociety/za-hansard/pull/75 might be a fix for this.
